name: charmap-ng-loong64

on:
  workflow_dispatch:

jobs:
  build:
    name: 编译构建 (loong64)
    runs-on: ubuntu-24.04

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 QEMU（loong64 模拟）
      uses: docker/setup-qemu-action@v3

    - name: 在 deepin-loong64 容器中编译
      run: |
        docker run --platform linux/loong64 \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          linuxdeepin/deepin:crimson-loong64 \
          bash -c '
            set -e

            apt update && apt upgrade -y
            apt install -y \
              python3-dev python3-pip build-essential \
              python3-pyqt6 pyqt6-dev-tools patchelf

            pip3 config set global.index-url https://mirrors.loong64.com/pypi/simple
            pip3 install nuitka==4.0.8 zstandard --break-system-packages

            nuitka --onefile --standalone --windows-console-mode=disable --windows-icon-from-ico=./ui/charmap.ico --show-progress --lto=yes --jobs=4 --enable-plugins=pyqt6 --include-data-dir=./ui=./ui charmap-ng.py
            mkdir ./charmap-ng
            cp *.bin ./charmap-ng/
          '

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: charmap-ng-loong64
        path: ./charmap-ng
